packages:
    - "tools/perspective-test"
    - "tools/perspective-scripts"
    - "tools/perspective-bench"
    - "cpp/perspective"
    - "packages/perspective-client"
    - "packages/perspective-esbuild-plugin"
    - "packages/perspective-viewer-datagrid"
    - "packages/perspective-viewer-d3fc"
    - "packages/perspective-viewer-openlayers"
    - "packages/perspective-workspace"
    - "packages/perspective-jupyterlab"
    - "packages/perspective-webpack-plugin"
    - "packages/perspective-cli"
    - "rust/generate-metadata"
    - "rust/perspective"
    - "rust/perspective-js"
    - "rust/perspective-viewer"
    - "rust/perspective-python"
    - "examples/*"
    - "docs"
