/******************************************************************************
 *
 * Copyright (c) 2017, the Perspective Authors.
 *
 * This file is part of the Perspective library, distributed under the terms of
 * the Apache License 2.0.  The full license can be found in the LICENSE file.
 *
 */

import style from "../less/workspace.less";
import template from "../html/workspace.html";
import {bindTemplate} from "@finos/perspective-viewer/dist/esm/utils";
import {PerspectiveWorkspace, SIDE} from "./workspace";
import {MessageLoop} from "@lumino/messaging";
import {Widget} from "@lumino/widgets";

import injectedStyles from "../less/injected.less";

@bindTemplate(template, style) // eslint-disable-next-line no-unused-vars
class PerspectiveWorkspaceElement extends HTMLElement {
    /**
     * The side the master panel is placed relative to the main panel.
     *
     * @param {('left'|'right')} value
     */
    set side(value) {
        this.setAttribute("side", value);
        if (this.workspace) {
            this.workspace.side = value;
        }
    }

    get side() {
        return this.getAttribute("side");
    }

    /**
     * Persist this layout to a serializable layout config object.  The returned
     * layout config can be supplied to the `restore()` method to reset this
     * workspace.  Tables are not saved - these must be added separately
     * via `addTable()`.
     *
     * @returns {Object} A layout config object.
     * @example
     * // Save this layout to local storage
     * const workspace = document.querySelector("perspective-workspace");
     * localStorage.set("CONFIG", JSON.stringify(workspace.save()));
     */
    save() {
        return this.workspace.save();
    }

    /**
     * Restore this workspace to a state as generated by reciprocal call 'save'
     *
     * @param {Object} config A serialized layout configuration.
     * @example
     * // Restore this layout from local storage
     * const workspace = document.querySelector("perspective-workspace");
     * workspace.restore(JSON.parse(localStorage.get("CONFIG"));
     */
    restore(layout) {
        return this.workspace.restore(layout);
    }

    addTable(name, table) {
        this.workspace.addTable(name, table);
    }

    getTable(name) {
        return this.workspace.getTable(name);
    }

    removeTable(name) {
        return this.workspace.removeTable(name);
    }

    /**
     * Invalidate this component's dimensions and recalculate.
     */
    notifyResize() {
        this.workspace.update();
    }

    connectedCallback() {
        this.side = this.side || SIDE.LEFT;

        const container = this.shadowRoot.querySelector("#container");
        this.workspace = new PerspectiveWorkspace(this, {side: this.side});

        // TODO: check we only insert one of these
        this._injectStyle = injectStyles("workspace-injected-stylesheet", injectedStyles);

        MessageLoop.sendMessage(this.workspace, Widget.Msg.BeforeAttach);
        container.insertBefore(this.workspace.node, null);
        MessageLoop.sendMessage(this.workspace, Widget.Msg.AfterAttach);

        window.onresize = () => {
            this.workspace.update();
        };
    }

    disconnectedCallback() {
        document.head.removeChild(this._injectStyle);
    }
}

const injectStyles = (name, style) => {
    const node = document.createElement("style");
    node.id = name;
    node.innerHTML = style;
    document.head.appendChild(node);
    return node;
};
